TICKERS = {
    "crypto": [
        {"symbol": "BTC-USD", "name": "Bitcoin"},
        {"symbol": "ETH-USD", "name": "Ethereum"},
        {"symbol": "BNB-USD", "name": "BNB"},
        {"symbol": "SOL-USD", "name": "Solana"},
        {"symbol": "XRP-USD", "name": "XRP"},
        {"symbol": "ADA-USD", "name": "Cardano"},
        {"symbol": "AVAX-USD", "name": "Avalanche"},
        {"symbol": "DOGE-USD", "name": "Dogecoin"},
        {"symbol": "DOT-USD", "name": "Polkadot"},
        {"symbol": "LINK-USD", "name": "Chainlink"},
        {"symbol": "UNI7083-USD", "name": "Uniswap"},
        {"symbol": "ATOM-USD", "name": "Cosmos"},
        {"symbol": "LTC-USD", "name": "Litecoin"},
        {"symbol": "BCH-USD", "name": "Bitcoin Cash"},
        {"symbol": "NEAR-USD", "name": "NEAR Protocol"},
        {"symbol": "ARB-USD", "name": "Arbitrum"},
        {"symbol": "OP-USD", "name": "Optimism"},
        {"symbol": "FIL-USD", "name": "Filecoin"},
    ],

    "commodities": [
        {"symbol": "GC=F", "name": "Gold"},
        {"symbol": "SI=F", "name": "Silver"},
        {"symbol": "PL=F", "name": "Platinum"},
        {"symbol": "PA=F", "name": "Palladium"},
        {"symbol": "HG=F", "name": "Copper"},
        {"symbol": "CL=F", "name": "Crude Oil (WTI)"},
        {"symbol": "BZ=F", "name": "Crude Oil (Brent)"},
        {"symbol": "NG=F", "name": "Natural Gas"},
        {"symbol": "ZW=F", "name": "Wheat"},
        {"symbol": "ZC=F", "name": "Corn"},
        {"symbol": "ZS=F", "name": "Soybeans"},
        {"symbol": "CC=F", "name": "Cocoa"},
        {"symbol": "KC=F", "name": "Coffee"},
        {"symbol": "CT=F", "name": "Cotton"},
        {"symbol": "SB=F", "name": "Sugar"},
        {"symbol": "LE=F", "name": "Live Cattle"},
        {"symbol": "HE=F", "name": "Lean Hogs"},
        {"symbol": "OJ=F", "name": "Orange Juice"},
    ],

    "etf_broad": [
        {"symbol": "VWCE.DE", "name": "Vanguard FTSE All-World (VWCE)"},
        {"symbol": "IWDA.AS", "name": "iShares MSCI World (IWDA)"},
        {"symbol": "CSPX.AS", "name": "iShares Core S&P 500 (CSPX)"},
        {"symbol": "EIMI.L", "name": "iShares MSCI Emerging Markets (EIMI)"},
        {"symbol": "EXSA.DE", "name": "iShares MSCI Europe (EXSA)"},
        {"symbol": "SPY", "name": "SPDR S&P 500 (SPY)"},
        {"symbol": "QQQ", "name": "Invesco NASDAQ-100 (QQQ)"},
        {"symbol": "VTI", "name": "Vanguard Total Stock Market (VTI)"},
        {"symbol": "IWM", "name": "iShares Russell 2000 (IWM)"},
        {"symbol": "VEA", "name": "Vanguard FTSE Developed Markets (VEA)"},
        {"symbol": "VWO", "name": "Vanguard FTSE Emerging Markets (VWO)"},
        {"symbol": "EFA", "name": "iShares MSCI EAFE (EFA)"},
        {"symbol": "EEM", "name": "iShares MSCI Emerging Markets (EEM)"},
        {"symbol": "ACWI", "name": "iShares MSCI ACWI (ACWI)"},
        {"symbol": "VT", "name": "Vanguard Total World Stock (VT)"},
        {"symbol": "VXUS", "name": "Vanguard Total International Stock (VXUS)"},
        {"symbol": "VWRL.AS", "name": "Vanguard FTSE All-World Dist"},
        {"symbol": "VUAA.L", "name": "Vanguard S&P 500 Acc"},
        {"symbol": "VEVE.AS", "name": "Vanguard FTSE Developed World"},
        {"symbol": "IUSQ.DE", "name": "iShares MSCI ACWI"},
        {"symbol": "SXR8.DE", "name": "iShares Core S&P500"},
        {"symbol": "EUNL.DE", "name": "iShares Core MSCI World"},
        {"symbol": "IS3N.DE", "name": "iShares Core EM IMI"},
        {"symbol": "SSAC.L", "name": "iShares MSCI ACWI UCITS"},
        {"symbol": "VWRA.L", "name": "Vanguard FTSE All World Acc"},
    ],

    "etf_dividend": [
        {"symbol": "VIG", "name": "Vanguard Dividend Appreciation (VIG)"},
        {"symbol": "SCHD", "name": "Schwab US Dividend Equity (SCHD)"},
        {"symbol": "HDV", "name": "iShares Core High Dividend (HDV)"},
        {"symbol": "DVY", "name": "iShares Select Dividend (DVY)"},
        {"symbol": "DGRO", "name": "iShares Core Dividend Growth (DGRO)"},
        {"symbol": "NOBL", "name": "ProShares S&P 500 Dividend Aristocrats (NOBL)"},
        {"symbol": "SDY", "name": "SPDR S&P Dividend (SDY)"},
        {"symbol": "VHYL.AS", "name": "Vanguard FTSE All-World High Div (VHYL)"},
        {"symbol": "JEPI", "name": "JPMorgan Equity Premium Income (JEPI)"},
        {"symbol": "JEPQ", "name": "JPMorgan NASDAQ Equity Premium Income (JEPQ)"},
    ],

    "etf_bonds": [
        {"symbol": "TLT", "name": "iShares 20+ Year Treasury Bond (TLT)"},
        {"symbol": "IEF", "name": "iShares 7-10 Year Treasury Bond (IEF)"},
        {"symbol": "SHY", "name": "iShares 1-3 Year Treasury Bond (SHY)"},
        {"symbol": "AGG", "name": "iShares Core US Aggregate Bond (AGG)"},
        {"symbol": "BND", "name": "Vanguard Total Bond Market (BND)"},
        {"symbol": "HYG", "name": "iShares High Yield Corporate Bond (HYG)"},
        {"symbol": "LQD", "name": "iShares Investment Grade Corporate Bond (LQD)"},
        {"symbol": "TIP", "name": "iShares TIPS Bond (TIP)"},
        {"symbol": "IGLT.L", "name": "iShares UK Gilts (IGLT)"},
    ],

    "etf_tech": [
        {"symbol": "XLK", "name": "Technology Select Sector (XLK)"},
        {"symbol": "VGT", "name": "Vanguard Information Technology (VGT)"},
        {"symbol": "SOXX", "name": "iShares Semiconductor (SOXX)"},
        {"symbol": "SMH", "name": "VanEck Semiconductor (SMH)"},
        {"symbol": "IGV", "name": "iShares Expanded Tech-Software (IGV)"},
        {"symbol": "SKYY", "name": "First Trust Cloud Computing (SKYY)"},
        {"symbol": "CLOU", "name": "Global X Cloud Computing (CLOU)"},
        {"symbol": "BUG", "name": "Global X Cybersecurity (BUG)"},
        {"symbol": "CIBR", "name": "First Trust NASDAQ Cybersecurity (CIBR)"},
        {"symbol": "HACK", "name": "ETFMG Prime Cyber Security (HACK)"},
        {"symbol": "AIQ", "name": "Global X AI & Technology (AIQ)"},
        {"symbol": "BOTZ", "name": "Global X Robotics & AI (BOTZ)"},
        {"symbol": "ROBO", "name": "ROBO Global Robotics & Automation (ROBO)"},
        {"symbol": "ARKK", "name": "ARK Innovation (ARKK)"},
        {"symbol": "ARKW", "name": "ARK Next Generation Internet (ARKW)"},
        {"symbol": "BLOK", "name": "Amplify Blockchain (BLOK)"},
        {"symbol": "BITQ", "name": "Bitwise Crypto Industry Innovators (BITQ)"},
    ],

    "etf_energy_materials": [
        {"symbol": "XLE", "name": "Energy Select Sector (XLE)"},
        {"symbol": "VDE", "name": "Vanguard Energy (VDE)"},
        {"symbol": "ICLN", "name": "iShares Global Clean Energy (ICLN)"},
        {"symbol": "QCLN", "name": "First Trust Clean Edge Green Energy (QCLN)"},
        {"symbol": "NLR", "name": "VanEck Uranium+Nuclear Energy (NLR)"},
        {"symbol": "URA", "name": "Global X Uranium (URA)"},
        {"symbol": "URNM", "name": "Sprott Uranium Miners (URNM)"},
        {"symbol": "COPX", "name": "Global X Copper Miners (COPX)"},
        {"symbol": "CPER", "name": "US Copper Index Fund (CPER)"},
        {"symbol": "HYDW", "name": "Global X Hydrogen (HYDW)"},
        {"symbol": "GDX", "name": "VanEck Gold Miners (GDX)"},
        {"symbol": "GDXJ", "name": "VanEck Junior Gold Miners (GDXJ)"},
        {"symbol": "XLB", "name": "Materials Select Sector (XLB)"},
        {"symbol": "XLI", "name": "Industrial Select Sector (XLI)"},
    ],

    "etf_other_sectors": [
        {"symbol": "XLF", "name": "Financial Select Sector (XLF)"},
        {"symbol": "XLV", "name": "Health Care Select Sector (XLV)"},
        {"symbol": "XLP", "name": "Consumer Staples Select Sector (XLP)"},
        {"symbol": "XLY", "name": "Consumer Discretionary Select Sector (XLY)"},
        {"symbol": "XLRE", "name": "Real Estate Select Sector (XLRE)"},
        {"symbol": "XLU", "name": "Utilities Select Sector (XLU)"},
        {"symbol": "XLC", "name": "Communication Services Select Sector (XLC)"},
        {"symbol": "IBB", "name": "iShares Biotechnology (IBB)"},
        {"symbol": "XBI", "name": "SPDR S&P Biotech (XBI)"},
        {"symbol": "VNQ", "name": "Vanguard Real Estate (VNQ)"},
        {"symbol": "IYR", "name": "iShares US Real Estate (IYR)"},
        {"symbol": "KIE", "name": "SPDR S&P Insurance (KIE)"},
        {"symbol": "KBE", "name": "SPDR S&P Bank (KBE)"},
    ],

    "market_indexes": [
    {"symbol":"SPY","name":"S&P500"},
    {"symbol":"QQQ","name":"Nasdaq100"},
    {"symbol":"DIA","name":"Dow Jones"},
    {"symbol":"IWM","name":"Russell2000"},
    {"symbol":"VTI","name":"Total US Market"},
    {"symbol":"VEA","name":"Developed Markets"},
    {"symbol":"VWO","name":"Emerging Markets"},
    {"symbol":"VT","name":"Total World"},
    {"symbol":"GLD","name":"Gold ETF"},
    {"symbol":"TLT","name":"20Y Treasury"},
    {"symbol":"UUP","name":"US Dollar"},
    {"symbol":"VNQ","name":"Real Estate"},
    ],

    "stocks_europe": [
        {"symbol": "ASML.AS", "name": "ASML"},
        {"symbol": "SHELL.AS", "name": "Shell"},
        {"symbol": "ADYEN.AS", "name": "Adyen"},
        {"symbol": "HEIA.AS", "name": "Heineken"},
        {"symbol": "PHIA.AS", "name": "Philips"},
        {"symbol": "NN.AS", "name": "NN Group"},
        {"symbol": "RAND.AS", "name": "Randstad"},
        {"symbol": "WKL.AS", "name": "Wolters Kluwer"},
        {"symbol": "INGA.AS", "name": "ING Group"},
        {"symbol": "MC.PA", "name": "LVMH"},
        {"symbol": "OR.PA", "name": "L\'Oréal"},
        {"symbol": "AIR.PA", "name": "Airbus"},
        {"symbol": "BNP.PA", "name": "BNP Paribas"},
        {"symbol": "SAN.PA", "name": "Sanofi"},
        {"symbol": "TTE.PA", "name": "TotalEnergies"},
        {"symbol": "RI.PA", "name": "Pernod Ricard"},
        {"symbol": "CAP.PA", "name": "Capgemini"},
        {"symbol": "DSY.PA", "name": "Dassault Systèmes"},
        {"symbol": "SU.PA", "name": "Schneider Electric"},
        {"symbol": "SIE.DE", "name": "Siemens"},
        {"symbol": "SAP.DE", "name": "SAP"},
        {"symbol": "BMW.DE", "name": "BMW"},
        {"symbol": "VOW3.DE", "name": "Volkswagen"},
        {"symbol": "ALV.DE", "name": "Allianz"},
        {"symbol": "DTE.DE", "name": "Deutsche Telekom"},
        {"symbol": "BAYN.DE", "name": "Bayer"},
        {"symbol": "MBG.DE", "name": "Mercedes-Benz"},
        {"symbol": "MUV2.DE", "name": "Munich Re"},
        {"symbol": "DBK.DE", "name": "Deutsche Bank"},
        {"symbol": "RWE.DE", "name": "RWE"},
        {"symbol": "BAS.DE", "name": "BASF"},
        {"symbol": "EOAN.DE", "name": "E.ON"},
        {"symbol": "HEN3.DE", "name": "Henkel"},
        {"symbol": "ADS.DE", "name": "Adidas"},
        {"symbol": "NOVO-B.CO", "name": "Novo Nordisk"},
        {"symbol": "MAERSK-B.CO", "name": "Maersk"},
        {"symbol": "NESN.SW", "name": "Nestlé"},
        {"symbol": "NOVN.SW", "name": "Novartis"},
        {"symbol": "ABBN.SW", "name": "ABB"},
        {"symbol": "ZURN.SW", "name": "Zurich Insurance"},
        {"symbol": "LONN.SW", "name": "Lonza"},
        {"symbol": "AZN.L", "name": "AstraZeneca"},
        {"symbol": "HSBA.L", "name": "HSBC"},
        {"symbol": "BP.L", "name": "BP"},
        {"symbol": "GSK.L", "name": "GSK"},
        {"symbol": "RIO.L", "name": "Rio Tinto"},
        {"symbol": "ULVR.L", "name": "Unilever"},
        {"symbol": "DGE.L", "name": "Diageo"},
        {"symbol": "BATS.L", "name": "BAT"},
        {"symbol": "LSEG.L", "name": "London Stock Exchange Group"},
        {"symbol": "PRU.L", "name": "Prudential"},
        {"symbol": "CPG.L", "name": "Compass Group"},
        {"symbol": "STAN.L", "name": "Standard Chartered"},
        {"symbol": "ANTO.L", "name": "Antofagasta"},
        {"symbol": "ENI.MI", "name": "ENI"},
        {"symbol": "ENEL.MI", "name": "Enel"},
        {"symbol": "ISP.MI", "name": "Intesa Sanpaolo"},
        {"symbol": "UCG.MI", "name": "UniCredit"},
        {"symbol": "STLAM.MI", "name": "Stellantis"},
        {"symbol": "ITX.MC", "name": "Inditex (Zara)"},
        {"symbol": "SAN.MC", "name": "Banco Santander"},
        {"symbol": "BBVA.MC", "name": "BBVA"},
        {"symbol": "IBE.MC", "name": "Iberdrola"},
        {"symbol": "TEF.MC", "name": "Telefónica"},
    ],

    "stocks_asia": [
        {"symbol": "0700.HK", "name": "Tencent"},
        {"symbol": "9988.HK", "name": "Alibaba"},
        {"symbol": "0005.HK", "name": "HSBC Asia"},
        {"symbol": "9618.HK", "name": "JD.com"},
        {"symbol": "3690.HK", "name": "Meituan"},
        {"symbol": "0388.HK", "name": "Hong Kong Exchanges"},
        {"symbol": "2318.HK", "name": "Ping An Insurance"},
        {"symbol": "0939.HK", "name": "CCB"},
        {"symbol": "1299.HK", "name": "AIA Group"},
        {"symbol": "0941.HK", "name": "China Mobile"},
        {"symbol": "600519.SS", "name": "Kweichow Moutai"},
        {"symbol": "601398.SS", "name": "ICBC"},
        {"symbol": "600036.SS", "name": "China Merchants Bank"},
        {"symbol": "601288.SS", "name": "Agricultural Bank of China"},
        {"symbol": "600900.SS", "name": "Yangtze Power"},
        {"symbol": "000858.SZ", "name": "Wuliangye Yibin"},
        {"symbol": "000333.SZ", "name": "Midea Group"},
        {"symbol": "000651.SZ", "name": "Gree Electric"},
        {"symbol": "002594.SZ", "name": "BYD"},
        {"symbol": "7203.T", "name": "Toyota"},
        {"symbol": "6758.T", "name": "Sony"},
        {"symbol": "9432.T", "name": "NTT"},
        {"symbol": "6861.T", "name": "Keyence"},
        {"symbol": "9984.T", "name": "SoftBank"},
        {"symbol": "8306.T", "name": "Mitsubishi UFJ"},
        {"symbol": "6367.T", "name": "Daikin"},
        {"symbol": "4519.T", "name": "Chugai Pharmaceutical"},
        {"symbol": "9433.T", "name": "KDDI"},
        {"symbol": "8316.T", "name": "Sumitomo Mitsui"},
        {"symbol": "7974.T", "name": "Nintendo"},
        {"symbol": "6954.T", "name": "Fanuc"},
        {"symbol": "9020.T", "name": "East Japan Railway"},
        {"symbol": "005930.KS", "name": "Samsung Electronics"},
        {"symbol": "000660.KS", "name": "SK Hynix"},
        {"symbol": "005490.KS", "name": "POSCO"},
        {"symbol": "035420.KS", "name": "Naver"},
        {"symbol": "051910.KS", "name": "LG Chem"},
        {"symbol": "RELIANCE.NS", "name": "Reliance Industries"},
        {"symbol": "TCS.NS", "name": "Tata Consultancy Services"},
        {"symbol": "INFY.NS", "name": "Infosys"},
        {"symbol": "HDFCBANK.NS", "name": "HDFC Bank"},
        {"symbol": "ICICIBANK.NS", "name": "ICICI Bank"},
        {"symbol": "HINDUNILVR.NS", "name": "Hindustan Unilever"},
        {"symbol": "BAJFINANCE.NS", "name": "Bajaj Finance"},
    ],

    "stocks_us_technology": [
        {"symbol": "NVDA", "name": "NVIDIA"},
        {"symbol": "AAPL", "name": "Apple"},
        {"symbol": "GOOGL", "name": "Alphabet Class A"},
        {"symbol": "GOOG", "name": "Alphabet Class C Capital Stock"},
        {"symbol": "MSFT", "name": "Microsoft"},
        {"symbol": "AVGO", "name": "Broadcom"},
        {"symbol": "META", "name": "Meta Platforms Class A"},
        {"symbol": "MU", "name": "Micron Technology"},
        {"symbol": "AMD", "name": "Advanced Micro Devices"},
        {"symbol": "ORCL", "name": "Oracle"},
        {"symbol": "INTC", "name": "Intel"},
        {"symbol": "LRCX", "name": "Lam Research"},
        {"symbol": "AMAT", "name": "Applied Materials"},
        {"symbol": "GE", "name": "GE Aerospace"},
        {"symbol": "PLTR", "name": "Palantir Technologies Class A"},
        {"symbol": "IBM", "name": "International Business Machines"},
        {"symbol": "KLAC", "name": "KLA"},
        {"symbol": "TXN", "name": "Texas Instruments Incorporated"},
        {"symbol": "MRVL", "name": "Marvell Technology"},
        {"symbol": "DELL", "name": "Dell Technologies Class C"},
        {"symbol": "SNDK", "name": "Sandisk"},
        {"symbol": "QCOM", "name": "QUALCOMM Incorporated"},
        {"symbol": "PANW", "name": "Palo Alto Networks"},
        {"symbol": "ADI", "name": "Analog Devices"},
        {"symbol": "WDC", "name": "Western Digital"},
        {"symbol": "APP", "name": "Applovin Class A"},
        {"symbol": "CRWD", "name": "CrowdStrike Holdings Class A"},
        {"symbol": "APH", "name": "Amphenol"},
        {"symbol": "NEE", "name": "NextEra Energy"},
        {"symbol": "CRM", "name": "Salesforce"},
        {"symbol": "VRT", "name": "Vertiv Holdings LLC Class A"},
        {"symbol": "NOW", "name": "ServiceNow"},
        {"symbol": "CDNS", "name": "Cadence Design Systems"},
        {"symbol": "FTNT", "name": "Fortinet"},
        {"symbol": "ADBE", "name": "Adobe"},
        {"symbol": "NET", "name": "Cloudflare Class A"},
        {"symbol": "SNPS", "name": "Synopsys"},
        {"symbol": "DDOG", "name": "Datadog Class A"},
        {"symbol": "SNOW", "name": "Snowflake"},
        {"symbol": "INTU", "name": "Intuit"},
        {"symbol": "COHR", "name": "Coherent"},
        {"symbol": "MPWR", "name": "Monolithic Power Systems"},
        {"symbol": "EMR", "name": "Emerson Electric Company"},
        {"symbol": "HPE", "name": "Hewlett Packard Enterprise Company"},
        {"symbol": "DASH", "name": "DoorDash Class A"},
        {"symbol": "MSI", "name": "Motorola Solutions"},
        {"symbol": "ALAB", "name": "Astera Labs"},
        {"symbol": "CRWV", "name": "CoreWeave Class A"},
        {"symbol": "MCHP", "name": "Microchip Technology Incorporated"},
        {"symbol": "ON", "name": "ON Semiconductor"},
        {"symbol": "ADSK", "name": "Autodesk"},
        {"symbol": "GFS", "name": "GlobalFoundries Ordinary Shares"},
        {"symbol": "CBRS", "name": "Cerebras Systems Class A"},
        {"symbol": "MSTR", "name": "Strategy Inc Class A"},
        {"symbol": "MCHPP", "name": "Microchip Technology Incorporated Depositary Shares Each Representing a 1/20th Interest in a Share of 7.50% Series A Mandatory Convertible Preferred Stock"},
        {"symbol": "XYZ", "name": "Block Class A"},
        {"symbol": "CRDO", "name": "Credo Technology Group Holding Ltd Ordinary Shares"},
        {"symbol": "JBL", "name": "Jabil"},
        {"symbol": "WDAY", "name": "Workday Class A"},
        {"symbol": "TWLO", "name": "Twilio Class A"},
        {"symbol": "RDDT", "name": "Reddit Class A"},
        {"symbol": "NTAP", "name": "NetApp"},
        {"symbol": "UI", "name": "Ubiquiti"},
        {"symbol": "FSLR", "name": "First Solar"},
        {"symbol": "ROP", "name": "Roper Technologies"},
        {"symbol": "STRC", "name": "Strategy Inc Variable Rate Series A Perpetual Stretch Preferred Stock"},
        {"symbol": "STRF", "name": "Strategy Inc 10.00% Series A Perpetual Strife Preferred Stock"},
        {"symbol": "Q", "name": "Qnity Electronics"},
        {"symbol": "RBLX", "name": "Roblox Class A"},
        {"symbol": "ZM", "name": "Zoom Communications Class A"},
        {"symbol": "MDB", "name": "MongoDB Class A"},
        {"symbol": "MTSI", "name": "MACOM Technology Solutions Holdings"},
        {"symbol": "VEEV", "name": "Veeva Systems Class A"},
        {"symbol": "SMCI", "name": "Super Micro Computer"},
        {"symbol": "CW", "name": "Curtiss-Wright"},
        {"symbol": "OTIS", "name": "Otis Worldwide"},
        {"symbol": "VRSN", "name": "VeriSign"},
        {"symbol": "P", "name": "Everpure Class A common stock"},
        {"symbol": "HUBB", "name": "Hubbell Inc"},
        {"symbol": "CTSH", "name": "Cognizant Technology Solutions Class A"},
    ],

    "stocks_us_finance": [
        {"symbol": "JPM", "name": "JP Morgan Chase & Co."},
        {"symbol": "BAC", "name": "Bank of America"},
        {"symbol": "MS", "name": "Morgan Stanley"},
        {"symbol": "GS", "name": "Goldman Sachs Group (The)"},
        {"symbol": "WFC", "name": "Wells Fargo & Company"},
        {"symbol": "C", "name": "Citigroup"},
        {"symbol": "AXP", "name": "American Express Company"},
        {"symbol": "BLK", "name": "BlackRock"},
        {"symbol": "SCHW", "name": "Charles Schwab (The)"},
        {"symbol": "IBKR", "name": "Interactive Brokers Group Class A"},
        {"symbol": "SPGI", "name": "S&P Global"},
        {"symbol": "PGR", "name": "Progressive (The)"},
        {"symbol": "COF", "name": "Capital One Financial"},
        {"symbol": "BNY", "name": "The Bank of New York Mellon"},
        {"symbol": "CME", "name": "CME Group Class A"},
        {"symbol": "PNC", "name": "PNC Financial Services Group (The)"},
        {"symbol": "BX", "name": "Blackstone"},
        {"symbol": "USB", "name": "U.S. Bancorp"},
        {"symbol": "KKR", "name": "KKR & Co."},
        {"symbol": "ICE", "name": "Intercontinental Exchange"},
        {"symbol": "HOOD", "name": "Robinhood Markets Class A"},
        {"symbol": "MCO", "name": "Moody\'s"},
        {"symbol": "MRSH", "name": "Marsh"},
        {"symbol": "APO", "name": "Apollo Global Management (New)"},
        {"symbol": "AON", "name": "Aon plc Class A Ordinary Shares (Ireland)"},
        {"symbol": "TRV", "name": "The Travelers Companies"},
        {"symbol": "TFC", "name": "Truist Financial"},
        {"symbol": "AFL", "name": "AFLAC Incorporated"},
        {"symbol": "ALL", "name": "Allstate (The)"},
        {"symbol": "AJG", "name": "Arthur J. Gallagher & Co."},
        {"symbol": "MET", "name": "MetLife"},
        {"symbol": "HBANL", "name": "Huntington Bancshares Incorporated Depositary Shares Each Representing a 1/40th Interest in a Share of 6.875% Series J Non-Cumulative Perpetual Preferred Stock"},
        {"symbol": "NDAQ", "name": "Nasdaq"},
        {"symbol": "FITB", "name": "Fifth Third Bancorp"},
        {"symbol": "STT", "name": "State Street"},
        {"symbol": "COIN", "name": "Coinbase Global Class A"},
        {"symbol": "ARES", "name": "Ares Management Class A"},
        {"symbol": "HBANM", "name": "Huntington Bancshares Incorporated Depositary Shares each representing a 1/1000th interest in a share of Huntington Series I Preferred Stock"},
        {"symbol": "HBANZ", "name": "Huntington Bancshares Incorporated Depositary Shares Each Representing a 1/1000th Interest in a Share of 5.50% Series L Non-Cumulative Perpetual Preferred Stock"},
        {"symbol": "AMP", "name": "Ameriprise Financial"},
        {"symbol": "AIG", "name": "American International Group New"},
        {"symbol": "CBRE", "name": "CBRE Group Inc Class A"},
        {"symbol": "RKT", "name": "Rocket Companies Class A"},
        {"symbol": "PRU", "name": "Prudential Financial"},
        {"symbol": "HIG", "name": "The Hartford Insurance Group"},
        {"symbol": "HBAN", "name": "Huntington Bancshares Incorporated"},
        {"symbol": "HBANP", "name": "Huntington Bancshares Incorporated Depositary Shares 4.500% Series H Non-Cumulative Perpetual Preferred Stock"},
        {"symbol": "MTB", "name": "M&T Bank"},
        {"symbol": "NTRS", "name": "Northern Trust"},
        {"symbol": "RJF", "name": "Raymond James Financial"},
        {"symbol": "CFG", "name": "Citizens Financial Group"},
        {"symbol": "CINF", "name": "Cincinnati Financial"},
        {"symbol": "WRB", "name": "W.R. Berkley"},
        {"symbol": "RF", "name": "Regions Financial"},
        {"symbol": "SYF", "name": "Synchrony Financial"},
        {"symbol": "TW", "name": "Tradeweb Markets Class A"},
        {"symbol": "FCNCA", "name": "First Citizens BancShares Class A"},
        {"symbol": "FITBM", "name": "Fifth Third Bancorp Depositary Shares Representing a 1/40th Ownership Interest in a Share of 6.875% Fixed-Rate Reset Non-Cumulative Perpetual Preferred Stock Series M"},
        {"symbol": "KEY", "name": "KeyCorp"},
        {"symbol": "LPLA", "name": "LPL Financial Holdings"},
    ],

    "stocks_us_healthcare": [
        {"symbol": "LLY", "name": "Eli Lilly and Company"},
        {"symbol": "JNJ", "name": "Johnson & Johnson"},
        {"symbol": "ABBV", "name": "AbbVie"},
        {"symbol": "UNH", "name": "UnitedHealth Group Incorporated (DE)"},
        {"symbol": "MRK", "name": "Merck & Company (new)"},
        {"symbol": "PM", "name": "Philip Morris International Inc"},
        {"symbol": "AMGN", "name": "Amgen"},
        {"symbol": "GILD", "name": "Gilead Sciences"},
        {"symbol": "ABT", "name": "Abbott Laboratories"},
        {"symbol": "ISRG", "name": "Intuitive Surgical"},
        {"symbol": "PFE", "name": "Pfizer"},
        {"symbol": "MO", "name": "Altria Group"},
        {"symbol": "BMY", "name": "Bristol-Myers Squibb Company"},
        {"symbol": "SYK", "name": "Stryker"},
        {"symbol": "VRTX", "name": "Vertex Pharmaceuticals Incorporated"},
        {"symbol": "MDT", "name": "Medtronic plc. Ordinary Shares"},
        {"symbol": "MCK", "name": "McKesson"},
        {"symbol": "ELV", "name": "Elevance Health"},
        {"symbol": "HCA", "name": "HCA Healthcare"},
        {"symbol": "MMM", "name": "3M Company"},
        {"symbol": "CI", "name": "The Cigna Group"},
        {"symbol": "BSX", "name": "Boston Scientific"},
        {"symbol": "REGN", "name": "Regeneron Pharmaceuticals"},
        {"symbol": "COR", "name": "Cencora"},
        {"symbol": "EW", "name": "Edwards Lifesciences"},
        {"symbol": "CAH", "name": "Cardinal Health"},
        {"symbol": "MDLN", "name": "Medline Class A"},
        {"symbol": "IDXX", "name": "IDEXX Laboratories"},
        {"symbol": "HUM", "name": "Humana"},
        {"symbol": "BDX", "name": "Becton Dickinson and Company"},
        {"symbol": "ALNY", "name": "Alnylam Pharmaceuticals"},
        {"symbol": "BTSGU", "name": "BrightSpring Health Services Tangible Equity Unit"},
        {"symbol": "ZTS", "name": "Zoetis Class A"},
        {"symbol": "RVMD", "name": "Revolution Medicines"},
        {"symbol": "NTRA", "name": "Natera"},
        {"symbol": "RPRX", "name": "Royalty Pharma plc Class A Ordinary Shares"},
        {"symbol": "IQV", "name": "IQVIA Holdings"},
        {"symbol": "CNC", "name": "Centene"},
        {"symbol": "GEHC", "name": "GE HealthCare Technologies"},
        {"symbol": "BIIB", "name": "Biogen"},
        {"symbol": "RMD", "name": "ResMed"},
        {"symbol": "DXCM", "name": "DexCom"},
        {"symbol": "ILMN", "name": "Illumina"},
        {"symbol": "UTHR", "name": "United Therapeutics"},
        {"symbol": "INSM", "name": "Insmed Incorporated"},
        {"symbol": "WST", "name": "West Pharmaceutical Services"},
        {"symbol": "DGX", "name": "Quest Diagnostics Incorporated"},
        {"symbol": "LH", "name": "Labcorp Holdings"},
        {"symbol": "STE", "name": "STERIS plc (Ireland) Ordinary Shares"},
        {"symbol": "MRNA", "name": "Moderna"},
        {"symbol": "INCY", "name": "Incyte"},
        {"symbol": "ULS", "name": "UL Solutions Class A"},
        {"symbol": "VTRS", "name": "Viatris"},
        {"symbol": "GH", "name": "Guardant Health"},
        {"symbol": "NBIX", "name": "Neurocrine Biosciences"},
        {"symbol": "ZBH", "name": "Zimmer Biomet Holdings"},
        {"symbol": "SOLV", "name": "Solventum"},
        {"symbol": "THC", "name": "Tenet Healthcare"},
        {"symbol": "EXEL", "name": "Exelixis"},
        {"symbol": "BBIO", "name": "BridgeBio Pharma"},
    ],

    "stocks_us_consumer": [
        {"symbol": "AMZN", "name": "Amazon.com"},
        {"symbol": "WMT", "name": "Walmart"},
        {"symbol": "V", "name": "Visa"},
        {"symbol": "COST", "name": "Costco Wholesale"},
        {"symbol": "MA", "name": "Mastercard Incorporated"},
        {"symbol": "NFLX", "name": "Netflix"},
        {"symbol": "PG", "name": "Procter & Gamble Company (The)"},
        {"symbol": "HD", "name": "Home Depot (The)"},
        {"symbol": "MCD", "name": "McDonald\'s"},
        {"symbol": "TJX", "name": "TJX Companies (The)"},
        {"symbol": "DIS", "name": "Walt Disney Company (The)"},
        {"symbol": "UBER", "name": "Uber Technologies"},
        {"symbol": "BKNG", "name": "Booking Holdings"},
        {"symbol": "LOW", "name": "Lowe\'s Companies"},
        {"symbol": "SBUX", "name": "Starbucks"},
        {"symbol": "MAR", "name": "Marriott International Class A"},
        {"symbol": "ABNB", "name": "Airbnb Class A"},
        {"symbol": "RCL", "name": "Royal Caribbean Cruises Ltd."},
        {"symbol": "FDX", "name": "FedEx"},
        {"symbol": "HLT", "name": "Hilton Worldwide Holdings"},
        {"symbol": "ROST", "name": "Ross Stores"},
        {"symbol": "SHW", "name": "Sherwin-Williams Company (The)"},
        {"symbol": "ORLY", "name": "O\'Reilly Automotive"},
        {"symbol": "CVNA", "name": "Carvana Co. Class A"},
        {"symbol": "ECL", "name": "Ecolab"},
        {"symbol": "CL", "name": "Colgate-Palmolive Company"},
        {"symbol": "URI", "name": "United Rentals"},
        {"symbol": "WBD", "name": "Warner Bros. Discovery Series A"},
        {"symbol": "BKR", "name": "Baker Hughes Company Class A"},
        {"symbol": "NKE", "name": "Nike"},
        {"symbol": "PCAR", "name": "PACCAR"},
        {"symbol": "SE", "name": "Sea Limited American Depositary Shares each representing one Class A Ordinary Share"},
        {"symbol": "TGT", "name": "Target"},
        {"symbol": "FAST", "name": "Fastenal Company"},
        {"symbol": "DAL", "name": "Delta Air Lines"},
        {"symbol": "EA", "name": "Electronic Arts"},
        {"symbol": "AZO", "name": "AutoZone"},
        {"symbol": "EBAY", "name": "eBay"},
        {"symbol": "MSCI", "name": "MSCI"},
        {"symbol": "ASTS", "name": "AST SpaceMobile Class A"},
        {"symbol": "DHI", "name": "D.R. Horton"},
        {"symbol": "YUM", "name": "Yum! Brands"},
        {"symbol": "TTWO", "name": "Take-Two Interactive Software"},
        {"symbol": "VIK", "name": "Viking Holdings Ltd Ordinary Shares"},
        {"symbol": "CCL", "name": "Carnival Ltd. Common Shares"},
        {"symbol": "TKO", "name": "TKO Group Holdings Class A"},
        {"symbol": "LYV", "name": "Live Nation Entertainment"},
        {"symbol": "TRI", "name": "Thomson Reuters Common Shares"},
        {"symbol": "CMG", "name": "Chipotle Mexican Grill"},
        {"symbol": "SATS", "name": "EchoStar"},
        {"symbol": "SYY", "name": "Sysco"},
        {"symbol": "UAL", "name": "United Airlines Holdings"},
        {"symbol": "LVS", "name": "Las Vegas Sands"},
        {"symbol": "KVUE", "name": "Kenvue"},
        {"symbol": "KMB", "name": "Kimberly-Clark"},
        {"symbol": "EL", "name": "Estee Lauder Companies (The)"},
        {"symbol": "FISV", "name": "Fiserv"},
        {"symbol": "CPNG", "name": "Coupang Class A"},
        {"symbol": "CPRT", "name": "Copart (DE)"},
        {"symbol": "TPR", "name": "Tapestry"},
    ],

    "stocks_us_industrials": [
        {"symbol": "TSLA", "name": "Tesla"},
        {"symbol": "CAT", "name": "Caterpillar"},
        {"symbol": "RTX", "name": "RTX"},
        {"symbol": "TMO", "name": "Thermo Fisher Scientific Inc"},
        {"symbol": "BA", "name": "Boeing Company (The)"},
        {"symbol": "GLW", "name": "Corning Incorporated"},
        {"symbol": "DE", "name": "Deere & Company"},
        {"symbol": "UNP", "name": "Union Pacific"},
        {"symbol": "HON", "name": "Honeywell International"},
        {"symbol": "DHR", "name": "Danaher"},
        {"symbol": "LMT", "name": "Lockheed Martin"},
        {"symbol": "PH", "name": "Parker-Hannifin"},
        {"symbol": "PWR", "name": "Quanta Services"},
        {"symbol": "HWM", "name": "Howmet Aerospace"},
        {"symbol": "UPS", "name": "United Parcel Service"},
        {"symbol": "CMI", "name": "Cummins"},
        {"symbol": "ADP", "name": "Automatic Data Processing"},
        {"symbol": "GD", "name": "General Dynamics"},
        {"symbol": "CSX", "name": "CSX"},
        {"symbol": "NOC", "name": "Northrop Grumman"},
        {"symbol": "GM", "name": "General Motors Company"},
        {"symbol": "ITW", "name": "Illinois Tool Works"},
        {"symbol": "CTAS", "name": "Cintas"},
        {"symbol": "BRKRP", "name": "Bruker 6.375% Mandatory Convertible Preferred Stock Series A"},
        {"symbol": "RKLB", "name": "Rocket Lab"},
        {"symbol": "NSC", "name": "Norfolk Southern"},
        {"symbol": "TDG", "name": "Transdigm Group Incorporated"},
        {"symbol": "FIX", "name": "Comfort Systems USA"},
        {"symbol": "TER", "name": "Teradyne"},
        {"symbol": "F", "name": "Ford Motor Company"},
        {"symbol": "GWW", "name": "W.W. Grainger"},
        {"symbol": "NUE", "name": "Nucor"},
        {"symbol": "KEYS", "name": "Keysight Technologies"},
        {"symbol": "LHX", "name": "L3Harris Technologies"},
        {"symbol": "CARR", "name": "Carrier Global"},
        {"symbol": "AME", "name": "AMETEK"},
        {"symbol": "ROK", "name": "Rockwell Automation"},
        {"symbol": "ODFL", "name": "Old Dominion Freight Line"},
        {"symbol": "HEI", "name": "Heico"},
        {"symbol": "WAB", "name": "Westinghouse Air Brake Technologies"},
        {"symbol": "AXON", "name": "Axon Enterprise"},
        {"symbol": "STLD", "name": "Steel Dynamics"},
        {"symbol": "A", "name": "Agilent Technologies"},
        {"symbol": "PYPL", "name": "PayPal Holdings"},
        {"symbol": "EME", "name": "EMCOR Group"},
        {"symbol": "WAT", "name": "Waters"},
        {"symbol": "VMC", "name": "Vulcan Materials Company (Holding Company)"},
        {"symbol": "PAYX", "name": "Paychex"},
        {"symbol": "MLM", "name": "Martin Marietta Materials"},
        {"symbol": "STRL", "name": "Sterling Infrastructure"},
    ],

    "stocks_us_energy": [
        {"symbol": "XOM", "name": "Exxon Mobil"},
        {"symbol": "CVX", "name": "Chevron"},
        {"symbol": "COP", "name": "ConocoPhillips"},
        {"symbol": "BE", "name": "Bloom Energy Class A"},
        {"symbol": "MPC", "name": "Marathon Petroleum"},
        {"symbol": "VLO", "name": "Valero Energy"},
        {"symbol": "EOG", "name": "EOG Resources"},
        {"symbol": "PSX", "name": "Phillips 66"},
        {"symbol": "OXY", "name": "Occidental Petroleum"},
        {"symbol": "MPLX", "name": "MPLX LP Common Units Representing Limited Partner Interests"},
        {"symbol": "FANG", "name": "Diamondback Energy"},
        {"symbol": "DVN", "name": "Devon Energy"},
        {"symbol": "EQT", "name": "EQT"},
        {"symbol": "HAL", "name": "Halliburton Company"},
        {"symbol": "TPL", "name": "Texas Pacific Land"},
        {"symbol": "EXE", "name": "Expand Energy"},
        {"symbol": "WWD", "name": "Woodward"},
        {"symbol": "PR", "name": "Permian Resources Class A"},
        {"symbol": "VNOM", "name": "Viper Energy Class A"},
        {"symbol": "PAA", "name": "Plains All American Pipeline L.P. Common Units representing Limited Partner Interests"},
        {"symbol": "SUN", "name": "Sunoco LP Common Units representing limited partner interests"},
        {"symbol": "APA", "name": "APA"},
        {"symbol": "DINO", "name": "HF Sinclair"},
        {"symbol": "LFUS", "name": "Littelfuse"},
        {"symbol": "AR", "name": "Antero Resources"},
        {"symbol": "POWL", "name": "Powell Industries"},
        {"symbol": "RRC", "name": "Range Resources"},
        {"symbol": "SM", "name": "SM Energy Company"},
        {"symbol": "CHRD", "name": "Chord Energy"},
        {"symbol": "NE", "name": "Noble plc A Ordinary Shares"},
        {"symbol": "MTDR", "name": "Matador Resources Company"},
        {"symbol": "VAL", "name": "Valaris Limited Common Shares"},
        {"symbol": "MUR", "name": "Murphy Oil"},
        {"symbol": "HCC", "name": "Warrior Met Coal"},
        {"symbol": "CRC", "name": "California Resources"},
        {"symbol": "MGY", "name": "Magnolia Oil & Gas Class A"},
        {"symbol": "LBRT", "name": "Liberty Energy Class A common stock"},
        {"symbol": "PBF", "name": "PBF Energy Class A"},
        {"symbol": "PLUG", "name": "Plug Power"},
        {"symbol": "HESM", "name": "Hess Midstream LP Class A Representing Limited Partner Interests"},
    ],

    "stocks_us_realestate": [
        {"symbol": "WELL", "name": "Welltower"},
        {"symbol": "PLD", "name": "Prologis"},
        {"symbol": "EQIX", "name": "Equinix REIT"},
        {"symbol": "AMT", "name": "American Tower (REIT)"},
        {"symbol": "SPG", "name": "Simon Property Group"},
        {"symbol": "DLR", "name": "Digital Realty Trust"},
        {"symbol": "O", "name": "Realty Income"},
        {"symbol": "PSA", "name": "Public Storage"},
        {"symbol": "CCI", "name": "Crown Castle"},
        {"symbol": "IRM", "name": "Iron Mountain Incorporated (Delaware)Common Stock REIT"},
        {"symbol": "VTR", "name": "Ventas"},
        {"symbol": "EXR", "name": "Extra Space Storage Inc"},
        {"symbol": "AGNCN", "name": "AGNC Investment Depositary Shares Each Representing a 1/1000th Interest in a Share of 7.00% Series C Fixed-To-Floating Rate Cumulative Redeemable Preferred Stock"},
        {"symbol": "AGNCO", "name": "AGNC Investment Depositary Shares each representing a 1/1000th interest in a share of 6.50% Series E Fixed-to-Floating Cumulative Redeemable Preferred Stock"},
        {"symbol": "VICI", "name": "VICI Properties"},
        {"symbol": "AGNCM", "name": "AGNC Investment Depositary Shares rep 6.875% Series D Fixed-to-Floating Cumulative Redeemable Preferred Stock"},
        {"symbol": "AGNCP", "name": "AGNC Investment Depositary Shares Each Representing a 1/1000th Interest in a Share of 6.125% Series F Fixed-to-Floating Rate Cumulative Redeemable Preferred Stock"},
        {"symbol": "AGNCL", "name": "AGNC Investment Depositary Shares Each Representing a 1/1000th Interest in a Share of 7.75% Series G Fixed-Rate Reset Cumulative Redeemable Preferred Stock"},
        {"symbol": "AVB", "name": "AvalonBay Communities"},
        {"symbol": "EQR", "name": "Equity Residential Common Shares of Beneficial Interest"},
        {"symbol": "SBAC", "name": "SBA Communications Class A"},
        {"symbol": "ESS", "name": "Essex Property Trust"},
        {"symbol": "WY", "name": "Weyerhaeuser Company"},
        {"symbol": "HST", "name": "Host Hotels & Resorts"},
        {"symbol": "WPC", "name": "W. P. Carey REIT"},
        {"symbol": "KIM", "name": "Kimco Realty (HC)"},
        {"symbol": "MAA", "name": "Mid-America Apartment Communities"},
        {"symbol": "NLY", "name": "Annaly Capital Management"},
        {"symbol": "LAMR", "name": "Lamar Advertising Company Class A"},
        {"symbol": "SUI", "name": "Sun Communities"},
    ],

    "stocks_us_utilities": [
        {"symbol": "SO", "name": "Southern Company (The)"},
        {"symbol": "CEG", "name": "Constellation Energy"},
        {"symbol": "DUK", "name": "Duke Energy (Holding Company)"},
        {"symbol": "WMB", "name": "Williams Companies (The)"},
        {"symbol": "WM", "name": "Waste Management"},
        {"symbol": "EPD", "name": "Enterprise Products Partners L.P."},
        {"symbol": "CIEN", "name": "Ciena"},
        {"symbol": "KMI", "name": "Kinder Morgan"},
        {"symbol": "AEP", "name": "American Electric Power Company"},
        {"symbol": "ET", "name": "Energy Transfer LP Common Units"},
        {"symbol": "RSG", "name": "Republic Services"},
        {"symbol": "SRE", "name": "DBA Sempra"},
        {"symbol": "D", "name": "Dominion Energy"},
        {"symbol": "TRGP", "name": "Targa Resources"},
        {"symbol": "OKE", "name": "ONEOK"},
        {"symbol": "VST", "name": "Vistra"},
        {"symbol": "LNG", "name": "Cheniere Energy"},
        {"symbol": "ETR", "name": "Entergy"},
        {"symbol": "XEL", "name": "Xcel Energy"},
        {"symbol": "EXC", "name": "Exelon"},
        {"symbol": "PCG", "name": "Pacific Gas & Electric Co."},
        {"symbol": "PEG", "name": "Public Service Enterprise Group Incorporated"},
        {"symbol": "ED", "name": "Consolidated Edison"},
        {"symbol": "WEC", "name": "WEC Energy Group"},
        {"symbol": "PPLC", "name": "PPL Corporate Units"},
        {"symbol": "VG", "name": "Venture Global Class A common stock"},
        {"symbol": "CQP", "name": "Cheniere Energy Partners LP Common Units"},
        {"symbol": "DTE", "name": "DTE Energy Company"},
        {"symbol": "AEE", "name": "Ameren"},
        {"symbol": "NRG", "name": "NRG Energy"},
    ],

    "stocks_us_staples": [
        {"symbol": "KO", "name": "Coca-Cola Company (The)"},
        {"symbol": "PEP", "name": "PepsiCo"},
        {"symbol": "CVS", "name": "CVS Health"},
        {"symbol": "MNST", "name": "Monster Beverage"},
        {"symbol": "MDLZ", "name": "Mondelez International Class A"},
        {"symbol": "CTVA", "name": "Corteva"},
        {"symbol": "KDP", "name": "Keurig Dr Pepper"},
        {"symbol": "ADM", "name": "Archer-Daniels-Midland Company"},
        {"symbol": "KR", "name": "Kroger Company (The)"},
        {"symbol": "HSY", "name": "The Hershey Company"},
        {"symbol": "KHC", "name": "The Kraft Heinz Company"},
        {"symbol": "BG", "name": "Bunge Limited Common Shares"},
        {"symbol": "STZ", "name": "Constellation Brands"},
        {"symbol": "TSN", "name": "Tyson Foods"},
        {"symbol": "GIS", "name": "General Mills"},
        {"symbol": "HRL", "name": "Hormel Foods"},
        {"symbol": "MKC", "name": "McCormick & Company Incorporated"},
        {"symbol": "COKE", "name": "Coca-Cola Consolidated"},
        {"symbol": "SJM", "name": "The J.M. Smucker Company"},
        {"symbol": "SFD", "name": "Smithfield Foods"},
        {"symbol": "DAR", "name": "Darling Ingredients"},
        {"symbol": "PRMB", "name": "Primo Brands Class A"},
        {"symbol": "ACI", "name": "Albertsons Companies Class A"},
        {"symbol": "SFM", "name": "Sprouts Farmers Market"},
        {"symbol": "CELH", "name": "Celsius Holdings"},
        {"symbol": "PPC", "name": "Pilgrim\'s Pride"},
        {"symbol": "CPB", "name": "The Campbell\'s Company"},
        {"symbol": "INGR", "name": "Ingredion Incorporated"},
        {"symbol": "CAG", "name": "ConAgra Brands"},
        {"symbol": "LW", "name": "Lamb Weston Holdings"},
    ],

    "stocks_us_telecom": [
        {"symbol": "CSCO", "name": "Cisco Systems (DE)"},
        {"symbol": "CCZ", "name": "Comcast Holdings ZONES"},
        {"symbol": "ANET", "name": "Arista Networks"},
        {"symbol": "TMUS", "name": "T-Mobile US"},
        {"symbol": "VZ", "name": "Verizon Communications"},
        {"symbol": "T", "name": "AT&T"},
        {"symbol": "TBB", "name": "AT&T 5.350% Global Notes due 2066"},
        {"symbol": "CMCSA", "name": "Comcast Class A"},
        {"symbol": "LITE", "name": "Lumentum Holdings"},
        {"symbol": "FFIV", "name": "F5"},
        {"symbol": "ROKU", "name": "Roku Class A"},
        {"symbol": "CHTR", "name": "Charter Communications Class A New"},
        {"symbol": "LUMN", "name": "Lumen Technologies"},
        {"symbol": "ESE", "name": "ESCO Technologies"},
        {"symbol": "LILPV", "name": "Liberty Latin America Ltd. 9.0% Fixed Rate Cumulative Perpetual Redeemable Series A Preference Shares"},
        {"symbol": "IRDM", "name": "Iridium Communications Inc"},
        {"symbol": "TDS", "name": "Telephone and Data Systems Common Shares"},
        {"symbol": "AD", "name": "Array Digital Infrastructure Common Shares"},
        {"symbol": "LBRDK", "name": "Liberty Broadband Class C"},
        {"symbol": "LBRDA", "name": "Liberty Broadband Class A"},
    ],

    "stocks_us_materials": [
        {"symbol": "LIN", "name": "Linde plc Ordinary Shares"},
        {"symbol": "SCCO", "name": "Southern Copper"},
        {"symbol": "NEM", "name": "Newmont"},
        {"symbol": "FCX", "name": "Freeport-McMoRan"},
        {"symbol": "APD", "name": "Air Products and Chemicals"},
        {"symbol": "SOMN", "name": "Southern Company (The) 2025 Series A Corporate Units"},
        {"symbol": "CDE", "name": "Coeur Mining"},
        {"symbol": "SOJE", "name": "Southern Company (The) Series 2020C 4.20% Junior Subordinated Notes due October 15 2060"},
        {"symbol": "IP", "name": "International Paper Company"},
        {"symbol": "MP", "name": "MP Materials"},
        {"symbol": "CLF", "name": "Cleveland-Cliffs"},
        {"symbol": "USAR", "name": "USA Rare Earth Class A"},
        {"symbol": "LPX", "name": "Louisiana-Pacific"},
        {"symbol": "FBIN", "name": "Fortune Brands Innovations"},
        {"symbol": "UFPI", "name": "UFP Industries"},
        {"symbol": "TREX", "name": "Trex Company"},
        {"symbol": "HYMC", "name": "Hycroft Mining Holding Class A"},
        {"symbol": "MTX", "name": "Minerals Technologies"},
        {"symbol": "SLVM", "name": "Sylvamo"},
        {"symbol": "IPX", "name": "IperionX Limited American Depositary Share"},
    ],

}


def get_all_symbols() -> list[str]:
    return [t['symbol'] for category in TICKERS.values() for t in category]


def get_all_tickers() -> list[dict]:
    result = []
    for category, items in TICKERS.items():
        for item in items:
            result.append({**item, 'category': category})
    return result


def get_by_category(category: str) -> list[dict]:
    return TICKERS.get(category, [])


if __name__ == "__main__":
    all_symbols = get_all_symbols()
    print(f"Total tickers: {len(all_symbols)}")
    for category, items in TICKERS.items():
        print(f"  {category}: {len(items)}")